# Generated by Django 5.1.1 on 2024-10-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Precio',
            new_name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'Ropa'), (2, 'Comida'), (3, 'Electrodomesticos')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
